# Generated by Django 4.2.4 on 2023-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="filename",
            new_name="file_name",
        ),
        migrations.AddField(
            model_name="file",
            name="file_identifier",
            field=models.CharField(default="exit", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
